version: "3"

services:
  postgres:
    image: "postgres:15.3-alpine3.18"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: concurrency
    volumes:
      - ./.db/postgres/:/var/lib/postgresql/data/
      - ./.db/db.sql:/docker-entrypoint-initdb.d/db.sql

  redis:
    image: "redis:6.0.20-alpine3.18"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./.db/redis/:/data

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
